config/routes.rb
Rails.application.routes.draw do
  resources :non_devise_users
  resources :user_awards
  resources :categories
  get '/' => "static#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user_award
end

app/models/non_devise_user.rb
class NonDeviseUser < ApplicationRecord
    has_many :user_awards
end

app/models/user_award.rb
class UserAward < ApplicationRecord
    belongs_to :non_devise_user
    has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:award_id, :nominees, :winner)
    end
end

app/controllers/non_devise_users_controller.rb
class NonDeviseUsersController < ApplicationController
  before_action :set_non_devise_user, only: %i[ show edit update destroy ]

  # GET /non_devise_users or /non_devise_users.json
  def index
    @non_devise_users = NonDeviseUser.all
  end

  # GET /non_devise_users/1 or /non_devise_users/1.json
  def show
  end

  # GET /non_devise_users/new
  def new
    @non_devise_user = NonDeviseUser.new
  end

  # GET /non_devise_users/1/edit
  def edit
  end

  # POST /non_devise_users or /non_devise_users.json
  def create
    @non_devise_user = NonDeviseUser.new(non_devise_user_params)

    respond_to do |format|
      if @non_devise_user.save
        format.html { redirect_to @non_devise_user, notice: "Non devise user was successfully created." }
        format.json { render :show, status: :created, location: @non_devise_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @non_devise_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /non_devise_users/1 or /non_devise_users/1.json
  def update
    respond_to do |format|
      if @non_devise_user.update(non_devise_user_params)
        format.html { redirect_to @non_devise_user, notice: "Non devise user was successfully updated." }
        format.json { render :show, status: :ok, location: @non_devise_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @non_devise_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /non_devise_users/1 or /non_devise_users/1.json
  def destroy
    @non_devise_user.destroy
    respond_to do |format|
      format.html { redirect_to non_devise_users_url, notice: "Non devise user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_non_devise_user
      @non_devise_user = NonDeviseUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def non_devise_user_params
      params.require(:non_devise_user).permit(:username, :password)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def home
    end
end

app/controllers/user_awards_controller.rb
class UserAwardsController < ApplicationController
  before_action :set_user_award, only: %i[ show edit update destroy ]

  # GET /user_awards or /user_awards.json
  def index
    @user_awards = UserAward.all
  end

  # GET /user_awards/1 or /user_awards/1.json
  def show
  end

  # GET /user_awards/new
  def new
    @user_award = UserAward.new
  end

  # GET /user_awards/1/edit
  def edit
  end

  # POST /user_awards or /user_awards.json
  def create
    @user_award = UserAward.new(user_award_params)

    respond_to do |format|
      if @user_award.save
        format.html { redirect_to @user_award, notice: "User award was successfully created." }
        format.json { render :show, status: :created, location: @user_award }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_awards/1 or /user_awards/1.json
  def update
    respond_to do |format|
      if @user_award.update(user_award_params)
        format.html { redirect_to @user_award, notice: "User award was successfully updated." }
        format.json { render :show, status: :ok, location: @user_award }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_awards/1 or /user_awards/1.json
  def destroy
    @user_award.destroy
    respond_to do |format|
      format.html { redirect_to user_awards_url, notice: "User award was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_award
      @user_award = UserAward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_award_params
      params.require(:user_award).permit(:year, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/non_devise_users_helper.rb
module NonDeviseUsersHelper
end

app/helpers/user_awards_helper.rb
module UserAwardsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :award_id %>
    <%= form.number_field :award_id %>
  </div>

  <div class="field">
    <%= form.label :nominees %>
    <%= form.text_area :nominees %>
  </div>

  <div class="field">
    <%= form.label :winner %>
    <%= form.text_field :winner %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Award</th>
      <th>Nominees</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.award_id %></td>
        <td><%= category.nominees %></td>
        <td><%= category.winner %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Award:</strong>
  <%= @category.award_id %>
</p>

<p>
  <strong>Nominees:</strong>
  <%= @category.nominees %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @category.winner %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AaSampleAwardsRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    </head>

  <style>

    body {
      padding: 5px;
      font-family: 'Quicksand', sans-serif;
    }
  </style>

  <body class="container-fluid">
  <div class="header">
  <nav>
      <ul id="nav-list">
          <li id="logout-button" class="nav-list-item"><%= button_to "Home", '/', method: :get  %></li>
          <li id="logout-button" class="nav-list-item"><%= button_to "Logout", destroy_user_session_path, method: :delete  %></li>
          <li id="logout-button" class="nav-list-item"><%= button_to "Awards", awards_path, method: :get  %></li>
          <li id="logout-button" class="nav-list-item"><%= button_to "Create Awards", new_award_path, method: :get  %></li>
      </ul>
  </nav>
</div>
    <%= yield %>
  </body>
</html>

app/views/non_devise_users/_form.html.erb
<%= form_with(model: non_devise_user) do |form| %>
  <% if non_devise_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(non_devise_user.errors.count, "error") %> prohibited this non_devise_user from being saved:</h2>

      <ul>
        <% non_devise_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/non_devise_users/edit.html.erb
<h1>Editing Non Devise User</h1>

<%= render 'form', non_devise_user: @non_devise_user %>

<%= link_to 'Show', @non_devise_user %> |
<%= link_to 'Back', non_devise_users_path %>

app/views/non_devise_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Non Devise Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @non_devise_users.each do |non_devise_user| %>
      <tr>
        <td><%= non_devise_user.username %></td>
        <td><%= non_devise_user.password %></td>
        <td><%= link_to 'Show', non_devise_user %></td>
        <td><%= link_to 'Edit', edit_non_devise_user_path(non_devise_user) %></td>
        <td><%= link_to 'Destroy', non_devise_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Non Devise User', new_non_devise_user_path %>

app/views/non_devise_users/new.html.erb
<h1>New Non Devise User</h1>

<%= render 'form', non_devise_user: @non_devise_user %>

<%= link_to 'Back', non_devise_users_path %>

app/views/non_devise_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @non_devise_user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @non_devise_user.password %>
</p>

<%= link_to 'Edit', edit_non_devise_user_path(@non_devise_user) %> |
<%= link_to 'Back', non_devise_users_path %>

app/views/user_awards/_form.html.erb
<%= form_with(model: user_award) do |form| %>
  <% if user_award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_award.errors.count, "error") %> prohibited this user_award from being saved:</h2>

      <ul>
        <% user_award.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_awards/edit.html.erb
<h1>Editing User Award</h1>

<%= render 'form', user_award: @user_award %>

<%= link_to 'Show', @user_award %> |
<%= link_to 'Back', user_awards_path %>

app/views/user_awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Awards</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_awards.each do |user_award| %>
      <tr>
        <td><%= user_award.year %></td>
        <td><%= user_award.user_id %></td>
        <td><%= link_to 'Show', user_award %></td>
        <td><%= link_to 'Edit', edit_user_award_path(user_award) %></td>
        <td><%= link_to 'Destroy', user_award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Award', new_user_award_path %>

app/views/user_awards/new.html.erb
<h1>New User Award</h1>

<%= render 'form', user_award: @user_award %>

<%= link_to 'Back', user_awards_path %>

app/views/user_awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @user_award.year %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_award.user_id %>
</p>

<%= link_to 'Edit', edit_user_award_path(@user_award) %> |
<%= link_to 'Back', user_awards_path %>